export const PUBLIC_JOB_SELECT = Object.freeze({
  id: true,
  title: true,
  company: true,
  location: true,
  description: true,
  category: true,
  type: true,
  salary: true,
  deadline: true,
  source: true,
  sourceUrl: true,
  featured: true,
  language: true,
  createdAt: true,
  updatedAt: true,
});
